services:
  tor:
    image: dperson/torproxy
    container_name: tor
    restart: unless-stopped
    command: -N
    ports:
      - "9050:9050"
    cpus: 0.2
    mem_limit: 100m

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11435:11434"
    restart: unless-stopped
    cpus: 4.5
    mem_limit: 8g

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=http://localhost:8080/
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
    depends_on:
      - tor
    ports:
      - "8080:8080"
    restart: always
    cpus: 0.8
    mem_limit: 512m

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SEARCH_API_URL=http://searxng:8080
      - WEBUI_AUTH=False
    ports:
      - "3000:8080"
    depends_on:
      - ollama
      - searxng
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m