services:
  tor:
    image: dperson/torproxy:latest
    ports:
      - "${TOR_PORT}:9050"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    environment:
      - TOR_LOG_LEVEL=notice
    volumes:
      - tor-data:/var/lib/tor
      - ./tor/torrc:/etc/tor/torrc:ro
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/9050' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - backend
    entrypoint:
      - sh
      - -c
      - |
        ollama serve &
        sleep 10
        ollama pull $${OLLAMA_MODEL}
        wait

  searxng:
    image: searxng/searxng:latest
    environment:
      - BASE_URL=${SEARXNG_BASE_URL:-http://0.0.0.0:8080/}
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    user: "root"
    volumes:
      - ./searxng/:/etc/searxng/:rw
      - ./searxng/cache:/var/cache/searxng:rw
    depends_on:
      - tor
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g
    tmpfs:
      - /tmp
      - /var/tmp
      - /var/log/uwsgi
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - backend

  webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      # Ollama connection
      - OLLAMA_BASE_URL=http://ollama:11434

      # SearxNG connection
      - SEARXNG_BASE_URL=http://searxng:8080
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&format=json

      # WebUI options
      - WEBUI_AUTH=False
      - DATA_DIR=/app/backend/data
      - ENABLE_VERSION_UPDATE_CHECK=false
      - SHOW_RELEASE_NOTES=false
      - WEBUI_SHOW_RELEASE_NOTES=false

      # RAG/Web Search
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - DEFAULT_RAG_WEB_SEARCH_ENABLED=true
      - ENABLE_RAG_WEB_LOADER=true

      # General Search
      - ENABLE_WEB_SEARCH=true
      - WEB_SEARCH_ENGINE=searxng
      - ENABLE_SEARCH=true
      - SEARCH_ENGINE=searxng

      # Tools/Function Calling
      - ENABLE_FUNCTION_CALLING=true
      - ENABLE_TOOLS=true

      # Telemetry
      - CHROMA_TELEMETRY_ENABLED=false
      - CORS_ALLOW_ORIGIN=http://localhost
    depends_on:
      - ollama
      - searxng
    ports:
      - "${WEBUI_PORT}:8080"
    volumes:
      - webui-data:/app/backend/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    networks:
      - backend

volumes:
  ollama-data:
    driver: local
  webui-data:
    driver: local
  tor-data:
    driver: local

networks:
  proxy:
    driver: bridge
  backend:
    driver: bridge