services:
  tor:
    image: dperson/torproxy:latest
    ports:
      - "${TOR_PORT:-9050}:9050"
    restart: unless-stopped
    cpus: 0.2
    mem_limit: 100m
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "localhost:9050", "https://check.torproject.org/"]
      interval: 30s
      timeout: 10s
      retries: 5
    read-only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

  ollama:
    image: ollama/ollama:latest
    ports:
      - "${OLLAMA_PORT:-11435}:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    cpus: 4
    mem_limit: 8g
    healthcheck:
      test: ["CMD-SHELL", "kill -0 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - backend

  searxng:
    image: searxng/searxng:latest
    environment:
      - BASE_URL=${SEARXNG_BASE_URL:-http://localhost:8080/}
      - http_proxy=socks5h://tor:9050
      - https_proxy=socks5h://tor:9050
    # volumes:
    #   - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
    depends_on:
      - tor
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    restart: always
    cpus: 0.8
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - backend

  webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - SEARCH_API_URL=http://searxng:8080
      - WEBUI_AUTH=False
      - CHROMA_TELEMETRY_ENABLED=FALSE
    depends_on:
      ollama:
        condition: service_healthy
      searxng:
        condition: service_healthy
    ports:
      - "${WEBUI_PORT:-3000}:8080"
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    read_only: true
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - backend

volumes:
  ollama-data:

networks:
  proxy:
    driver: bridge
  backend:
    driver: bridge