# Minimal privacy-focused SearXNG configuration
use_default_settings: true

server:
  # openssl rand -hex 32
  secret_key: "bb7272521323b0bf265c077e38bcb0fbba2336830f65a543b5913787684343fe"
  base_url: "http://localhost:8080/"
  port: 8080
  bind_address: "0.0.0.0"
  limiter: false
  public_instance: false
  image_proxy: true
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

general:
  instance_name: "SearXNG"
  enable_metrics: false
  debug: false

search:
  safe_search: 1
  autocomplete: ""
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  proxies:
    "all://": "socks5h://tor:9050"

ui:
  static_use_hash: true
  default_locale: ""
  default_theme: simple
  theme_args:
    simple_style: dark
  results_on_new_tab: false
  hotkeys: default

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false

# Added ownership fix for directories
ownership_fix:
  directories:
    - /etc/searxng
    - /var/cache/searxng