name: Test local-ai

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v2

      - name: Build services
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Check Ollama health
        run: |
          curl -f http://localhost:11435 || (echo "Ollama is not healthy" && docker compose logs ollama && exit 1)

      - name: Check SearXNG health
        run: |
          curl -f http://localhost:8080 || (echo "SearXNG is not healthy" && docker compose logs searxng && exit 1)

      - name: Check WebUI health
        run: |
          curl -f http://localhost:3000 || (echo "WebUI is not healthy" && docker compose logs webui && exit 1)

      - name: Tear down
        if: always()
        run: docker compose down